name: QuickSleep
main: io.github.rpod24.QuickSleep.QuickSleep
version: 1.5.5
api-version: 1.18
author: Ryan O'Donnell
description: "This plugin is a one person sleep plugin, where it will animate the time as the player sleeps for all players."
commands:
   QuickSleep:
      aliases: [myworlds, mw, worlds]
      description: These commands allow you to edit the rate and delay of the time increase when sleeping
      usage: /QuickSleep [setTimeCycle|setTimeDelay|help] [int] 
      permission: QuickSleep.quicksleep
      permission-message: You don't have permission